import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import TopDropdown from "@/components/TopDropdown";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-screen h-screen overflow-hidden`}
      >
        {/* Background image */}
        <Image
          src="/THEBACKGROUND.png"
          alt="Site Background"
          fill
          className="object-cover z-[-2]"
          priority
        />

        {/* Light dark overlay (10% black) */}
        <div className="fixed inset-0 bg-black/10 z-[-1]" />

        {/* Dropdown + page content */}
        <TopDropdown />
        {children}
      </body>
    </html>
  );
}
